### ISSUE TITLE
这能运行？？？

### ISSUE THREAD

**Issue by wongyue** [WelliJohn/StickScrollView#11]

**Comment by WelliJohn** [comment]
不维护了，官方有现成组件支持，注意下前言部分：在实现上述效果之后，用了下appbarlayout,觉得也能实现上述滑动的效果，不需要更改什么代码，体验上更好，具体可以看AndroidWidgetActivity，在这里面就是CollapsingToolbarLayout和appbarlayout的使用，完成上述的效果，可以简单看下实现的效果图
