### ISSUE TITLE
README.md里的布局已经过时啦

### ISSUE THREAD

**Issue by lyxsh1995** [WelliJohn/StickScrollView#3]
现在的控件名是 wellijohn.org.scrollviewwithstickheader.ScrollViewWithStickHeader
而且最好把java代码里必要设置写出来吧
        mStickScrollView.setContentView(mLLStickList);
        mStickScrollView.setSuspensionView(mViewBottom);

**Comment by WelliJohn** [comment]
不好意思，这么晚才看到，已经更新了
