### ISSUE TITLE
红米note4 android4.4版本ChildRecyclerView无法滑动

### ISSUE THREAD

**Issue by chengh2016** [WelliJohn/StickScrollView#5]

**Comment by WelliJohn** [comment]
已解决，在华为的4.4手机已经验证了，需要升级到1.1.0，另外需要调用下ScrollViewWithStickHeader的setRV方法，把你所有涉及到的ChildRecyclerView都设置进去就好了

**Comment by WelliJohn** [comment]
升级1.1.1的版本就好了，去掉了RV方法，无需设置了
