### ISSUE TITLE
子ScrollView 中的控件设置点击事件后,子ScrollView 不能捕获滑动事件?

### ISSUE THREAD

**Issue by ddyyuu** [WelliJohn/StickScrollView#6]

**Comment by WelliJohn** [comment]
试试1.1.7版本，我这边试了下可以了

**Comment by ddyyuu** [comment]
/*    @Override
    public boolean onTouchEvent(MotionEvent event) {
        if (mScrollViewWithStickHeader == null) {
            return super.onTouchEvent(event);
        }
        int action = event.getAction();

        if (action == MotionEvent.ACTION_DOWN) {
            mLastX = event.getX();
            mLastY = event.getY();
            //首先判断外层ScrollView是否滑动到底部
            if (mScrollViewWithStickHeader.isBottom()) {
                getParent().requestDisallowInterceptTouchEvent(true);
                return super.onTouchEvent(event);
            } else {
                //拦截事件 本身不处理
                getParent().requestDisallowInterceptTouchEvent(false);
                return false;
            }
        }
        if (action == MotionEvent.ACTION_MOVE) {
            float nowY = event.getY();
            if (!mScrollViewWithStickHeader.isBottom() && !isScrolledToTop && nowY - mLastY > 0) {
                if (Math.abs(event.getX() - mLastX) < minPageSlop) {
                    getParent().requestDisallowInterceptTouchEvent(true);
                    return super.onTouchEvent(event);
                } else {
                    getParent().requestDisallowInterceptTouchEvent(true);
                    return false;
                }
            } else if (mScrollViewWithStickHeader.isBottom() && !isScrolledToBottom && nowY - mLastY < 0) {
                if (Math.abs(event.getX() - mLastX) < minPageSlop) {
                    getParent().requestDisallowInterceptTouchEvent(true);
                    return super.onTouchEvent(event);
                } else {
                    getParent().requestDisallowInterceptTouchEvent(true);
                    return false;
                }
            } else if (mScrollViewWithStickHeader.isBottom() && !isScrolledToTop && nowY - mLastY > 0) {
                if (Math.abs(event.getX() - mLastX) < minPageSlop) {
                    getParent().requestDisallowInterceptTouchEvent(true);
                    return super.onTouchEvent(event);
                } else {
                    getParent().requestDisallowInterceptTouchEvent(true);
                    return false;
                }
            } else {
                getParent().requestDisallowInterceptTouchEvent(false);
            }
        }

        if (action == MotionEvent.ACTION_UP || action == MotionEvent.ACTION_CANCEL) {
            getParent().requestDisallowInterceptTouchEvent(false);
        }

        return super.onTouchEvent(event);
    }*/

	@Override
	public boolean dispatchTouchEvent(MotionEvent event) {
		if (mScrollViewWithStickHeader == null) {
			return super.onTouchEvent(event);
		}
		int action = event.getAction();

		if (action == MotionEvent.ACTION_DOWN) {
			mLastX = event.getX();
			mLastY = event.getY();
			//首先判断外层ScrollView是否滑动到底部
			if (mScrollViewWithStickHeader.isBottom()) {
				getParent().requestDisallowInterceptTouchEvent(true);
				return super.dispatchTouchEvent(event);
			} /*else {
				//拦截事件 本身不处理
				getParent().requestDisallowInterceptTouchEvent(false);
				return false;
			}*/
			return super.dispatchTouchEvent(event);
		}
		if (action == MotionEvent.ACTION_MOVE) {
			float nowY = event.getY();
			if (!mScrollViewWithStickHeader.isBottom() && !isScrolledToTop && nowY - mLastY > 0) {
				if (Math.abs(event.getX() - mLastX) < minPageSlop) {
					getParent().requestDisallowInterceptTouchEvent(true);
					return super.dispatchTouchEvent(event);
				} else {
					getParent().requestDisallowInterceptTouchEvent(true);
					return false;
				}
			} else if (mScrollViewWithStickHeader.isBottom() && !isScrolledToBottom && nowY - mLastY < 0) {
				if (Math.abs(event.getX() - mLastX) < minPageSlop) {
					getParent().requestDisallowInterceptTouchEvent(true);
					return super.dispatchTouchEvent(event);
				} else {
					getParent().requestDisallowInterceptTouchEvent(true);
					return false;
				}
			} else if (mScrollViewWithStickHeader.isBottom() && !isScrolledToTop && nowY - mLastY > 0) {
				if (Math.abs(event.getX() - mLastX) < minPageSlop) {
					getParent().requestDisallowInterceptTouchEvent(true);
					return super.dispatchTouchEvent(event);
				} else {
					getParent().requestDisallowInterceptTouchEvent(true);
					return false;
				}
			} else {
				getParent().requestDisallowInterceptTouchEvent(false);
			}
		}

		if (action == MotionEvent.ACTION_UP || action == MotionEvent.ACTION_CANCEL) {
			getParent().requestDisallowInterceptTouchEvent(false);
		}
		return super.dispatchTouchEvent(event);
	}
我是这样改的,可以解决问题.

**Comment by WelliJohn** [comment]
好的，条条大道通罗马，那我先关闭问题了。
