### ISSUE TITLE
setContentView方法bug

### ISSUE THREAD

**Issue by ftdguowei** [WelliJohn/StickScrollView#7]
你好，mStickScrollView.setContentView的方法我设置的没有问题，但是我是把tablayout换成了linelayout，然后linelayout往上滑动的时候，不能完全展示出来，会继续往上滑动接近一半的长度

**Comment by WelliJohn** [comment]
贴下布局看看呢

**Comment by ftdguowei** [comment]
这个我好像结局了，我发现一个新的问题不知道咋解决，就是当页面在最上面，我向下滑动下面的recycleview我希望可以是下拉刷新，但现在是最外层的scrollview抢了事件。。。

**Comment by WelliJohn** [comment]
你那边确认下是不是只要把scrollview的事件拦截放开就能解决问题？

**Comment by WelliJohn** [comment]
官方现成组件已经支持，用了下appbarlayout,觉得也能实现上述滑动的效果，不需要更改什么代码，体验上更好，具体可以看AndroidWidgetActivity，在这里面就是CollapsingToolbarLayout和appbarlayout的使用，完成上述的效果
