### ISSUE TITLE
相比Android现成的系统控件实现，此自定义的优势有哪些？

### ISSUE THREAD

**Issue by limuyang2** [WelliJohn/StickScrollView#8]
如题，希望解答，谢谢

**Comment by WelliJohn** [comment]
额，这个是因为之前没有找到这样的系统控件，相信好多看这篇github的人，都是因为没有找到这样的控件，如果有的话还请赐教，我也会加到readme里面。

**Comment by WelliJohn** [comment]
上次听你说过之后，我去找了下控件，找到了，谢谢，后面我会提醒大家的。
