### ISSUE TITLE
setContentView后还是 头部还是被隐藏了

### ISSUE THREAD

**Issue by deidaraz** [WelliJohn/StickScrollView#9]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white">

    <LinearLayout
        android:id="@+id/top_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <View
            android:layout_width="match_parent"
            android:layout_height="25dp"
            android:background="@color/transparent" />

        <RelativeLayout

            android:layout_width="match_parent"
            android:layout_height="@dimen/toolbar_height"
            android:layout_marginRight="@dimen/video_item_margin"
            android:background="@color/transparent"

            >

            <ImageView
                android:id="@+id/btn_back"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:src="@drawable/nav_back" />

            <TextView
                android:id="@+id/title"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_centerInParent="true"
                android:layout_toLeftOf="@id/btn_feedback"
                android:layout_toRightOf="@id/btn_back"
                android:ellipsize="end"
                android:gravity="center"
                android:maxEms="15"
                android:maxLines="1"
                android:textColor="@color/text_color"
                android:textSize="17sp" />

            <ImageView
                android:id="@+id/btn_share"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:layout_centerVertical="true"
                android:src="@drawable/nav_share_white" />
        </RelativeLayout>
    </LinearLayout>

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/game_poster"
        android:layout_width="match_parent"
        android:layout_height="221dp"
        app:actualImageScaleType="centerCrop"
        app:placeholderImage="@drawable/video_loading"
        app:placeholderImageScaleType="centerCrop" />

    <RelativeLayout
        android:id="@+id/layout_remark"
        android:layout_width="match_parent"
        android:layout_height="74dp"
        android:layout_alignParentBottom="true">

        <ImageView
            android:id="@+id/btn_remark"
            android:layout_width="match_parent"
            android:layout_height="44dp"
            android:layout_centerInParent="true"
            android:src="@drawable/detail_bt_comment" />

    </RelativeLayout>

    <wellijohn.org.scrollviewwithstickheader.ScrollViewWithStickHeader
        android:id="@+id/scrollview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_above="@id/layout_remark"
        android:layout_below="@id/top_bar"
        app:autoscroll="false">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:descendantFocusability="blocksDescendants"
            android:focusableInTouchMode="true"
            android:orientation="vertical">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/transparent"
                android:orientation="vertical"
                android:paddingTop="100dp">

                <com.facebook.drawee.view.SimpleDraweeView
                    android:id="@+id/game_cover"
                    android:layout_width="120dp"
                    android:layout_height="204dp"
                    android:layout_alignParentStart="true"
                    android:layout_alignParentTop="true"
                    android:layout_marginStart="22dp"
                    app:actualImageScaleType="centerCrop"
                    app:placeholderImage="@drawable/video_loading"
                    app:placeholderImageScaleType="centerCrop"
                    app:roundedCornerRadius="12dp" />
            </RelativeLayout>

            <LinearLayout
                android:id="@+id/layout_stick"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <com.flyco.tablayout.SlidingTabLayout
                    android:id="@+id/tab"
                    android:layout_width="wrap_content"
                    android:layout_height="51dp"
                    android:layout_below="@id/layout_remark_info"
                    android:layout_gravity="left"
                    app:tl_divider_padding="13dp"
                    app:tl_indicator_bounce_enable="true"
                    app:tl_indicator_color="#FAC000"
                    app:tl_indicator_corner_radius="2dp"
                    app:tl_indicator_height="3dp"
                    app:tl_indicator_width="21dp"
                    app:tl_tab_padding="22dp"
                    app:tl_textBold="SELECT"
                    app:tl_textSelectColor="@color/text_color"
                    app:tl_textUnselectColor="@color/text_tab_un_select_color"
                    app:tl_textsize="18sp" />

                <android.support.v4.view.ViewPager
                    android:id="@+id/vp_content"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/tab" />

                <View
                    android:layout_width="match_parent"
                    android:layout_height="1dp"
                    android:layout_below="@id/tab"
                    android:background="#ECECEC" />
            </LinearLayout>
        </LinearLayout>
    </wellijohn.org.scrollviewwithstickheader.ScrollViewWithStickHeader>

</RelativeLayout>

**Comment by WelliJohn** [comment]
在写这个框架的时候，没有注意Android原生控件的搭配也能实现效果，具体可以参看AndroidWidgetActivity。
